[package]
name = "picom"
version = "0.1.0"
edition = "2021"
links = "libpicom"

[dependencies]
bindgen = "0.69.4"
cc = "1.0.83"
pkg-config = "0.3.29"
walkdir = "2.4.0"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.83"
pkg-config = "0.3.29"
walkdir = "2.4.0"
